---
title: "LinumChromePlus"
author: "Marcial Escudero"
date: "2/14/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

Setting up the data for ChromePlus with stylar condition

```{r}
#install.packages("Rtools")
#install.packages("devtools")
#library(devtools)
#install_github('coleoguy/chromePlus')
#force=TRUE
library(chromePlus)
library(diversitree)

##Chromosome number and stylar states##
#Read the tree

tree <- read.tree("Linum.tree")
tree
tree <- drop.tip(tree, "L_oligophyllum")

#Read the data

dat1 <- read.csv("Linum_StylarDataset.csv", sep=",")
dat1

#Convert data appropiate for analysis. 6 y 36 son el min y el max n de cromosomas

setdiff(tree$tip.label, dat1$Name)
setdiff(dat1$Name,tree$tip.label)

#?datatoMatrix
dat.mat <- datatoMatrix(x=dat1, range= c(6,36), hyper=T)


# make the basic likelihood function
?make.mkn
lik <- make.mkn(tree = tree, states= dat.mat, k=ncol(dat.mat), strict = F, control = list(method="ode"))

# constrain the likelihood function to a biologically realistic design
#?constrainMkn
con.lik1 <- constrainMkn(data = dat.mat,
                        lik = lik,
                        polyploidy = F,
                        hyper = T,
                        constrain = list(drop.demi = F,
                                         drop.poly= F))
con.lik2 <- constrainMkn(data = dat.mat,
                        lik = lik,
                        constrain = list(nometa = T))

# lets make sure we have the parameters we expect
#?argnames
argnames(lik)
argnames(con.lik1)
argnames(con.lik2)
#Una vez que tenemos lik y con.lik, sigo utilizando diversitree
#Crear modelos ML con "lik" y con "con.lik"

con.fit1 <- find.mle(con.lik1, rep(0.1,10), method="subplex")

con.fit2 <- find.mle(con.lik2, rep(0.1,6), method="subplex")

con.fit1$par
con.fit2$par
anova(con.fit1, constrained=con.fit2)

p1 <- dat1[,2][dat1[,3]==0]
p2 <- dat1[,2][dat1[,3]==1]
b <- min(c(p1,p2)) -1 # Set the minimum for the breakpoints
e <- max(c(p1,p2)) +1 # Set the maximum for the breakpoints
ax <- pretty(b:e, n = 24) # Make a neat vector for the breakpoints
ax
h1 <- hist( p1, breaks = ax, plot = F)
h2 <- hist( p2, breaks = ax, plot = F)
c1 <- rgb(0,0,1,1/4)
c2 <- rgb(1,0,0,1/4)
plot(h2, col = c2, xlim= c(0,37), ylim = c(0,14), main="Heterostyly") # Plot 1st histogram using a transparent color
plot(h1, col = c1, add = TRUE) # Add 2nd 

```



Setting up the data for ChromePlus with distribution
```{r}


##Chromosome number and distribution##

#Read the tree

tree <- read.tree("Linum.tree")
tree
tree <- drop.tip(tree, "L_oligophyllum")

#Read the data

dat2 <- read.csv("Linum_distributionDataset.csv", sep=",")
dat2

#Convert data appropiate for analysis. 6 y 36 son el min y el max n de cromosomas

setdiff(tree$tip.label, dat2$Name)
setdiff(dat2$Name,tree$tip.label)

?datatoMatrix
dat.mat2 <- datatoMatrix(x=dat2, range= c(6,36), hyper=T)


# make the basic likelihood function

?is.ultrametric
is.ultrametric(tree)

?make.mkn

lik <- make.mkn(tree = tree, states= dat.mat2, k=ncol(dat.mat2), strict = F, control = list(method="ode"))


# constrain the likelihood function to a biologically realistic design

?constrainMkn

con.lik3 <- constrainMkn(data = dat.mat2,
                        lik = lik,
                        polyploidy = F,
                        hyper = T,
                        constrain = list(drop.demi = F,
                                         drop.poly= F))


con.lik4 <- constrainMkn(data = dat.mat2,
                        lik = lik,
                        constrain = list(nometa = T))

# lets make sure we have the parameters we expect
#?argnames
argnames(lik)
argnames(con.lik3)
argnames(con.lik4)
#Una vez que tenemos lik y con.lik, sigo utilizando diversitree
#Crear modelos ML con "lik" y con "con.lik"

con.fit3 <- find.mle(con.lik3, rep(0.1,10), method="subplex")

con.fit4 <- find.mle(con.lik4, rep(0.1,6), method="subplex")

con.fit3$par
con.fit4$par

anova(con.fit3, constrained=con.fit4)


p1 <- dat2[,2][dat2[,3]==0]
p2 <- dat2[,2][dat2[,3]==1]
b <- min(c(p1,p2)) -1 # Set the minimum for the breakpoints
e <- max(c(p1,p2)) +1 # Set the maximum for the breakpoints
ax <- pretty(b:e, n = 24) # Make a neat vector for the breakpoints
ax
h1 <- hist( p1, breaks = ax, plot = F)
h2 <- hist( p2, breaks = ax, plot = F)
c1 <- rgb(0,0,1,1/4)
c2 <- rgb(1,0,0,1/4)
plot(h1, col = c1, xlim= c(0,37), ylim = c(0,20), main="Distribution") # Plot 1st histogram using a transparent color
plot(h2, col = c2, add = TRUE) # Add 2nd 

```

Setting up the data for ChromePlus with annual vs. perennial

```{r}

##Chromosome number and distribution##

#Read the tree

tree <- read.tree("Linum.tree")
tree
tree <- drop.tip(tree, "L_oligophyllum")

#Read the data

mydata3 <- read.csv ("./taxonomy.csv")

setdiff(mydata3$Names2, tree$tip.label)
setdiff(tree$tip.label,mydata3$Names2)
mydata3$Names2 <- as.character(mydata3$Names2)
mydata3$Names2[mydata3$Names2=="606"] <- "L_virgatum"
mydata3$Names2[mydata3$Names2=="L_setaceum_Het"] <- "L_flos-carmini"
mydata3$Names2[mydata3$Names2=="L_thumbergii"] <- "L_thunbergii"
setdiff(mydata3$Names2, tree$tip.label)
setdiff(tree$tip.label,mydata3$Names2)
mydata3 <- mydata3[which(mydata3$Names2 %in% tree$tip.label),]
setdiff(mydata3$Names2, tree$tip.label)
setdiff(tree$tip.label,mydata3$Names2)

dat3 <- dat2

dat3[,3] <- mydata3[,8][match(dat2$Name,mydata3$Names2)]
dat3
#Convert data appropiate for analysis. 6 y 36 son el min y el max n de cromosomas

setdiff(tree$tip.label, dat3$Name)
setdiff(dat3$Name,tree$tip.label)

dat3 <- dat3[dat3[,3]!="?",]
setdiff(tree$tip.label, dat3$Name)
setdiff(dat3$Name,tree$tip.label)
tree <- drop.tip(tree,"L_prostratum")

?datatoMatrix
dat3[,3] <- as.numeric(dat3[,3])
dat.mat3 <- datatoMatrix(x=dat3, range= c(6,36), hyper=T)


# make the basic likelihood function

?is.ultrametric
is.ultrametric(tree)

?make.mkn

lik <- make.mkn(tree = tree, states= dat.mat3, k=ncol(dat.mat3), strict = F, control = list(method="ode"))


# constrain the likelihood function to a biologically realistic design

?constrainMkn

con.lik5 <- constrainMkn(data = dat.mat3,
                        lik = lik,
                        polyploidy = F,
                        hyper = T,
                        constrain = list(drop.demi = F,
                                         drop.poly= F))


con.lik6 <- constrainMkn(data = dat.mat3,
                        lik = lik,
                        constrain = list(nometa = T))

# lets make sure we have the parameters we expect
#?argnames
argnames(lik)
argnames(con.lik5)
argnames(con.lik6)
#Una vez que tenemos lik y con.lik, sigo utilizando diversitree
#Crear modelos ML con "lik" y con "con.lik"

con.fit5 <- find.mle(con.lik5, rep(0.1,10), method="subplex")

con.fit6 <- find.mle(con.lik6, rep(0.1,6), method="subplex")

con.fit5$par
con.fit6$par

anova(con.fit5, constrained=con.fit6)

mcmc.fit5 <- mcmc(con.lik5, coef(con.fit5), 100000, w = .3)

#relationship between annual vs perennial and diversification rates
phy <- tree
states <- dat3[,3]
names(states) <- dat3[,1]
lik <- make.bisse(phy, states)
lik
p <- starting.point.bisse(phy)
p
fit <- find.mle(lik, p)
fit
lik.l <- constrain(lik, mu1 ~ mu0)
fit.l <- find.mle(lik.l, p[argnames(lik.l)])
round(rbind(full=coef(fit), equal.l=coef(fit.l, TRUE)), 3)
anova(fit, equal.l=fit.l)

p1 <- dat3[,2][dat3[,3]==0]
p2 <- dat3[,2][dat3[,3]==1]
b <- min(c(p1,p2)) -1 # Set the minimum for the breakpoints
e <- max(c(p1,p2)) +1 # Set the maximum for the breakpoints
ax <- pretty(b:e, n = 24) # Make a neat vector for the breakpoints
ax
h1 <- hist( p1, breaks = ax, plot = F)
h2 <- hist( p2, breaks = ax, plot = F)
c1 <- rgb(0,0,1,1/4)
c2 <- rgb(1,0,0,1/4)
plot(h1, col = c1, xlim= c(0,37), ylim = c(0,14), main="Habit") # Plot 1st histogram using a transparent color
plot(h2, col = c2, add = TRUE) # Add 2nd 

```

